services:
    
  nc-db:
    image: mariadb:11.4-noble
    container_name: nc-db
    #depends_on:
    #  - traefik
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - ncnet
    volumes:
      - nc_maria_data:/var/lib/mysql:Z
      - type: tmpfs
        target: /dev/shm
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
  
  nc-redis:
    image: redis:8.0.2-alpine
    container_name: nc-redis
    restart: unless-stopped
    networks:
      - ncnet
  
  nc-nextcloud:
    image: d4void/nextcloud:31.0.5-apache
    container_name: nc-nextcloud
    depends_on:
      - nc-db
      - nc-redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
    networks:
      - ncnet
      - default
    volumes:
      - nc_nextcloud:/var/www/html:z
    environment:
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_HOST=nc-db
      - REDIS_HOST=nc-redis
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=MyTraefikNet"
      - "traefik.http.routers.nextcloudcontainer.rule=Host(`${NEXTCLOUD_FQDN}`)"
      - "traefik.http.routers.nextcloudcontainer.entrypoints=websecure"
      - "traefik.http.routers.nextcloudcontainer.tls=true"
      - "traefik.http.routers.nextcloudcontainer.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.nextcloudcontainer.middlewares=security@file"
      - "traefik.http.routers.nextcloudcontainer.service=mynextcloudservice"
      - "traefik.http.services.mynextcloudservice.loadbalancer.server.port=${JOPLIN_PORT}"
      - "traefik.http.services.mynextcloudservice.loadbalancer.server.scheme=http"


  nc-cron:
    image: d4void/nextcloud:31.0.5-apache
    container_name: nc-cron
    depends_on:
      - nc-db
      - nc-redis
    restart: unless-stopped
    networks:
      - ncnet
    volumes:
      - nc_nextcloud:/var/www/html:z
    entrypoint: /cron.sh

volumes:
  nc_maria_data:
    driver: local
    driver_opts:
      type: none
      device: ${NC_VOL}/var-lib-mysql
      o: bind
  nc_nextcloud:
    driver: local
    driver_opts:
      type: none
      device: ${NC_VOL}/nextcloud
      o: bind
  # nas_volume:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=adresse_ip_du_nas,rw
  #     device: ":/chemin/vers/le/partage"

networks:
  ncnet:
    internal: true
    name: MyNCnet
