# Dockerfile pour créer une image Nextcloud apache avec samba-client et le module php smbclient
#
# docker build -t d4void/nextcloud:31.0.5-apache -f Dockerfile.apache .

ARG VERSION=31.0.6
  
FROM nextcloud:${VERSION}-apache

RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends procps smbclient libsmbclient-dev; \
    rm -rf /var/lib/apt/lists/*; \
    pecl install smbclient; \
    docker-php-ext-enable smbclient; \
    rm -rf /tmp/pear/