services:
    
  nc-db:
    image: mariadb:11-noble
    container_name: nc-db
    #depends_on:
    #  - traefik
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - ncnet
    volumes:
      - nc_maria_data:/var/lib/mysql
      #- nc_maria_conf:/etc/mysql
      - type: tmpfs
        target: /dev/shm
    environment:
      - TZ=${TZ}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
  
  nc-nextcloud:
    image: nextcloud:31.0.5-apache
    container_name: nc-nextcloud
    depends_on:
      - nc-db
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    networks:
      - ncnet
      - default
    volumes:
      - nc_nextcloud:/var/www/html
    environment:
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_HOST=nc-db


volumes:
  nc_maria_data:
    driver: local
    driver_opts:
      type: none
      device: ${NC_VOL}/var-lib-mysql
      o: bind
  nc_maria_conf:
    driver: local
    driver_opts:
      type: none
      device: ${NC_VOL}/etc-mysql
      o: bind
  nc_nextcloud:
    driver: local
    driver_opts:
      type: none
      device: ${NC_VOL}/nextcloud
      o: bind
  # nas_volume:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=adresse_ip_du_nas,rw
  #     device: ":/chemin/vers/le/partage"

networks:
  ncnet:
    internal: true
    name: MyNCnet
